# My personal Starship config.

[git_status]
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
up_to_date = "âœ“"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

[nodejs]
format = "using [NodeJS $version](bold green) "

[username]
style_user = "bold blue"
format = "as user [$user]($style)
show_always = true

[hostname]
ssh_only = false
format =  "on host [$hostname](bold blue) in "
trim_at = ".companyname.com"
disabled = false

[golang]
format = "using [Go $version](bold cyan) "

[python]
python_binary = "python3"
format = "using [Python $version](bold blue) "

[java]
format = "using [Java $version](bold yellow) "

[character]                           
success_symbol = "[\\$](bold green)" 
error_symbol = "[\\$](bold red)"
